language: node_js

node_js:
  - 14

cache:
  # cache both npm modules and Cypress binary
  npm: true
  directories:
    - ~/.cache

override:
  - npm ci
  - npm run cy:verify
  - npm run cy:info

stages:
  - name: set variables
  - name: e2e tests 1
    if: commit_message =~ /.*test_travis.*/
  - name: e2e tests 2
    if: commit_message =~ /.*other.*/

jobs:
  include:
    - stage: set variables
      env:
        - STAGE_NAME="Tests on chrome"
      script: 
        - export COMMIT_INFO_MESSAGE=$(sh ./get_commit_message.sh)
        - echo $COMMIT_INFO_MESSAGE

    - stage: e2e tests 1
      script: 
        - npm run cy:run:record
        - kill $(jobs -p) || true
    - stage: e2e tests 2
      script: 
        - npm run cy:run:sos
        - kill $(jobs -p) || true
