language: node_js

node_js:
  #Node 10.3+ includes npm@6 which has good "npm ci" command
  - 10.8

cache:
  # cache both npm modules and Cypress binary
  npm: true
  directories:
    - ~/.cache

override:
  - npm ci
  - npm run cy:verify
  - npm run cy:info

defaults: &defaults
  script:
    - export COMMIT_INFO_MESSAGE="Testing Commit"
    - echo $COMMIT_INFO_MESSAGE
    - export MESSAGE=$(git log -n 1 --pretty=%B $(cut -d " " -f 2 <<< $(git log -n 1 --pretty=%B)))
    - echo $MESSAGE
    #- npm run cy:run:record
    - kill $(jobs -p) || true

jobs:
  include:
    - stage: test
      env:
        - STAGE_NAME="Tests on chrome"
      <<: *defaults
