language: node_js

node_js:
  #Node 10.3+ includes npm@6 which has good "npm ci" command
  - 10.8

cache:
  # cache both npm modules and Cypress binary
  directories:
    - ~/.npm
    - ~/.cache

override:
  - npm ci
  - npm run cy:verify
  - npm run cy:info

defaults: &defaults
  script:
    - npm run cy:run
    - kill $(jobs -p) || true

jobs:
  include:
    - stage: test
      env:
        - STAGE_NAME="Tests on chrome"
      <<: *defaults