language: node_js

node_js:
  - 14

cache:
  # cache both npm modules and Cypress binary
  npm: true
  directories:
    - ~/.cache

override:
  - npm ci
  - npm run cy:verify
  - npm run cy:info

stages:
  - name: test1
    if: commit_message =~ /.*test_travis.*/
  - name: test2
    if: commit_message =~ /.*other.*/
  
set-message: &set-message
  script:
    - export COMMIT_INFO_MESSAGE=$(sh ./get_commit_message.sh)

jobs:
  include:
    - stage: test1
      env:
        - STAGE_NAME="test on chrome"
      <<: *set-message
      script: npm run cy:run:record
    - stage: test2
      env:
        - STAGE_NAME="test on chrome"
      <<: *set-message
      script: npm run cy:run:sos
