language: node_js

node_js:
  #Node 10.3+ includes npm@6 which has good "npm ci" command
  - 10.8

cache:
  # cache both npm modules and Cypress binary
  npm: true
  directories:
    - ~/.cache

override:
  - npm ci
  - npm run cy:verify
  - npm run cy:info

defaults: &defaults
  script:
    - export COMMIT_INFO_MESSAGE=$(node -pe 'JSON.parse(process.argv[1]).builds.find(i => i.repository.name === "test_travis").commit.message' \
"$(curl -s -H "Travis-API-Version: 3" \
-H "User-Agent: API Explorer" \
-H "Authorization: token MTDTD5ilUbB5_1jGnM3yFA" \
  https://api.travis-ci.com/owner/rr-renjith/active))
    - echo $COMMIT_INFO_MESSAGE
    #- npm run cy:run:record
    - kill $(jobs -p) || true

jobs:
  include:
    - stage: test
      env:
        - STAGE_NAME="Tests on chrome"
      <<: *defaults
