language: node_js

node_js:
  - 14

cache:
  # cache both npm modules and Cypress binary
  npm: true
  directories:
    - ~/.cache

override:
  - npm ci
  - npm run cy:verify
  - npm run cy:info

stages:
  - name: set variables
  - name: e2e tests 1
    if: env(PARENT_BUILD) = test_travis
  - name: e2e tests 2
    if: env(PARENT_BUILD) = asset-hound

jobs:
  include:
    - stage: set variables
      env:
        - STAGE_NAME="Tests on chrome"
      script: sh ./get_commit_message.sh

    - stage: e2e tests 1
      script: 
        - npm run cy:run:record
        - kill $(jobs -p) || true
    - stage: e2e tests 2
      script: 
        - npm run cy:run:sos
        - kill $(jobs -p) || true
