language: node_js

node_js:
  - 14

cache:
  # cache both npm modules and Cypress binary
  npm: true
  directories:
    - ~/.cache

override:
  - npm ci
  - npm run cy:verify
  - npm run cy:info

stages:
  - name: test1
    if: commit_message =~ /.*test_travis.*/
  - name: test2
    if: commit_message =~ /.*other.*/

jobs:
  include:
    - env: STAGE_NAME="Tests on chrome"
    - stage: test1
      script:
        - export COMMIT_INFO_MESSAGE=$(sh ./get_commit_message.sh)
        - echo $COMMIT_INFO_MESSAGE
        - npm run cy:run:record
        - kill $(jobs -p) || true
    - stage: test2
      script:
        - export COMMIT_INFO_MESSAGE=$(sh ./get_commit_message.sh)
        - echo $COMMIT_INFO_MESSAGE
        - npm run cy:run:sos
        - kill $(jobs -p) || true
